version: '3'
services:
  app:
    build: .
    container_name: vite-app
    restart: always
    mem_limit: 1g
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
